// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type BpfEvent struct {
	At      uint64
	Ts      uint64
	Skb     uint64
	DataLen uint32
	_       [1]byte /* unsupported bitfield */
	Data    [1500]uint8
	_       [7]byte
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
}

// BpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	KprobeSkbByStackid *ebpf.ProgramSpec `ebpf:"kprobe_skb_by_stackid"`
	KprobeSkbFree      *ebpf.ProgramSpec `ebpf:"kprobe_skb_free"`
	KretprobeSkbBuild  *ebpf.ProgramSpec `ebpf:"kretprobe_skb_build"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	EventRingbuf *ebpf.MapSpec `ebpf:"event_ringbuf"`
	EventStash   *ebpf.MapSpec `ebpf:"event_stash"`
	SkbStackid   *ebpf.MapSpec `ebpf:"skb_stackid"`
	StackidSkb   *ebpf.MapSpec `ebpf:"stackid_skb"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	EventRingbuf *ebpf.Map `ebpf:"event_ringbuf"`
	EventStash   *ebpf.Map `ebpf:"event_stash"`
	SkbStackid   *ebpf.Map `ebpf:"skb_stackid"`
	StackidSkb   *ebpf.Map `ebpf:"stackid_skb"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.EventRingbuf,
		m.EventStash,
		m.SkbStackid,
		m.StackidSkb,
	)
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	KprobeSkbByStackid *ebpf.Program `ebpf:"kprobe_skb_by_stackid"`
	KprobeSkbFree      *ebpf.Program `ebpf:"kprobe_skb_free"`
	KretprobeSkbBuild  *ebpf.Program `ebpf:"kretprobe_skb_build"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeSkbByStackid,
		p.KprobeSkbFree,
		p.KretprobeSkbBuild,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
