name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
        env:
          GOPATH: ${{ env.HOME }}

      - name: Set up deps
        run: |
          sudo apt-get install -y gcc flex bison make autoconf libelf-dev
          git submodule update --init --recursive
          sudo make libpcap LIBPCAP_DIST_DIR=/usr/local CARCH=x86_64


      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean -p 1
        env:
          GOPATH: ${{ env.HOME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
